site_name: Aio Fluid
site_url: https://fluid.quantmind.com
repo_name: quantmind/aio-fluid
repo_url: https://github.com/quantmind/aio-fluid
strict: true
nav:
- Home: index.md
- Reference:
  - reference/index.md
  - reference/db.md
  - reference/db_cli.md
  - reference/db_crud.md
  - reference/db_migrations.md
  - reference/db_pagination.md
  - reference/dispatchers.md
  - reference/errors.md
  - reference/http_client.md
  - reference/task.md
  - reference/task_broker.md
  - reference/task_cli.md
  - reference/task_consumer.md
  - reference/task_manager.md
  - reference/task_plugin.md
  - reference/task_registry.md
  - reference/task_retry.md
  - reference/task_run.md
  - reference/task_scheduler.md
  - reference/task_scheduling.md
  - reference/utils.md
  - reference/workers.md
- Tutorials:
  - tutorials/index.md
  - tutorials/db.md
  - tutorials/dispatchers.md
  - tutorials/task_app.md
  - tutorials/task_broker.md
  - tutorials/task_k8s.md
  - tutorials/task_retry.md
  - tutorials/tasks.md
  - tutorials/workers.md
- comparison.md
- release-notes.md
theme:
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
    - navigation.instant
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - content.code.copy
  logo: assets/fluid-logo-dark.svg
hooks:
  - .dev/docs.py
plugins:
- search
- redirects:
    redirect_maps:
      tutorials/task_queue.md: tutorials/tasks.md
- mkdocstrings:
    handlers:
      python:
        options:
          show_root_heading: true
          show_if_no_docstring: true
          inherited_members: true
          members_order: source
          separate_signature: true
          unwrap_annotated: true
          filters:
          - '!^_'
          merge_init_into_class: true
          docstring_section_style: spacy
          signature_crossrefs: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          extensions:
          - griffe_typingdoc
          - griffe_pydantic:
              schema: false
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
