site_name: Aio Fluid
site_url: https://aio-fluid.com
repo_name: quantmind/aio-fluid
repo_url: https://github.com/quantmind/aio-fluid
theme:
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
    - navigation.instant
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - content.code.copy
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_root_heading: true
          show_if_no_docstring: true
          inherited_members: true
          members_order: source
          separate_signature: true
          unwrap_annotated: true
          filters:
          - '!^_'
          merge_init_into_class: true
          docstring_section_style: spacy
          signature_crossrefs: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          extensions:
          - griffe_typingdoc
          - griffe_pydantic:
              schema: false
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
