"""jsonb

Revision ID: d941c11ca25a
Revises: eae1cf7032bd
Create Date: 2026-06-05 16:09:21.529862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd941c11ca25a'
down_revision: Union[str, Sequence[str], None] = 'eae1cf7032bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fluid_tasks', 'params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('ix_fluid_tasks_params', 'fluid_tasks', ['params'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_fluid_tasks_queued'), 'fluid_tasks', ['queued'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fluid_tasks_queued'), table_name='fluid_tasks')
    op.drop_index('ix_fluid_tasks_params', table_name='fluid_tasks', postgresql_using='gin')
    op.alter_column('fluid_tasks', 'params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
