"""initial

Revision ID: eae1cf7032bd
Revises: 
Create Date: 2026-06-05 16:05:06.939033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae1cf7032bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fluid_tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Enum('init', 'queued', 'running', 'success', 'failure', 'aborted', 'rate_limited', 'interrupted', name='taskstate'), nullable=False),
    sa.Column('queued', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fluid_tasks_name'), 'fluid_tasks', ['name'], unique=False)
    op.create_index(op.f('ix_fluid_tasks_priority'), 'fluid_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_fluid_tasks_state'), 'fluid_tasks', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fluid_tasks_state'), table_name='fluid_tasks')
    op.drop_index(op.f('ix_fluid_tasks_priority'), table_name='fluid_tasks')
    op.drop_index(op.f('ix_fluid_tasks_name'), table_name='fluid_tasks')
    op.drop_table('fluid_tasks')
    # ### end Alembic commands ###
