"""initial

Revision ID: 1f91ed2b2f26
Revises: 
Create Date: 2024-08-18 10:19:38.372777

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f91ed2b2f26"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "multi_key",
        sa.Column("x", sa.JSON(), nullable=True),
        sa.Column("y", sa.JSON(), nullable=True),
    )
    op.create_table(
        "multi_key_unique",
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.UniqueConstraint("x", "y"),
    )
    op.create_table(
        "series",
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("group", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.UniqueConstraint("date", "group"),
    )
    op.create_index(op.f("ix_series_date"), "series", ["date"], unique=False)
    op.create_index(op.f("ix_series_group"), "series", ["group"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=False),
        sa.Column("done", sa.DateTime(timezone=True), nullable=True),
        sa.Column("severity", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("type", sa.Enum("todo", "issue", name="tasktype"), nullable=True),
        sa.Column("unique_title", sa.String(), nullable=True),
        sa.Column("story_points", sa.Numeric(), nullable=True),
        sa.Column("random", sa.String(length=64), nullable=True),
        sa.Column("subtitle", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("unique_title"),
    )
    op.create_table(
        "randoms",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("randomdate", sa.Date(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price", sa.Numeric(precision=100, scale=4), nullable=False),
        sa.Column("tenor", sa.String(length=3), nullable=False),
        sa.Column("tick", sa.Boolean(), nullable=True),
        sa.Column("info", sa.JSON(), nullable=True),
        sa.Column("jsonlist", sa.JSON(), nullable=True),
        sa.Column("task_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("randoms")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_series_group"), table_name="series")
    op.drop_index(op.f("ix_series_date"), table_name="series")
    op.drop_table("series")
    op.drop_table("multi_key_unique")
    op.drop_table("multi_key")
    # ### end Alembic commands ###
