#!/usr/bin/env bash

pkg_version=`python -c "import tomllib; d=tomllib.load(open('pyproject.toml','rb')); print('aio-fluid ' + d['project']['version'])"`
code=`uv run python -c 'import fluid; print(f"aio-fluid {fluid.__version__}")'`

echo ${pkg_version}

if [ "${pkg_version}" != "${code}" ]; then
    echo "ERROR: pyproject version ${pkg_version} different from code version ${code}"
    exit 1
fi
