#!/usr/bin/env bash

poetry=`poetry version`
code=`poetry run python -c 'import fluid; print(f"aio-fluid {fluid.__version__}")'`

echo ${poetry}

if [ "${poetry}" != "${code}" ]; then
    echo "ERROR: poetry version ${poetry} different from code version ${code}"
    exit 1
fi
